package com.aarvo.ui.theme

import androidx.compose.ui.graphics.Color

// AARVO reference UI palette: premium white surfaces + vivid royal purple + warm orange/gold accents.
val AarvoPrimary = Color(0xFF4B16D8)
val AarvoOnPrimary = Color(0xFFFFFFFF)
val AarvoPrimaryContainer = Color(0xFFEDE5FF)
val AarvoOnPrimaryContainer = Color(0xFF21005D)
val AarvoSecondary = Color(0xFFFF7A00)
val AarvoOnSecondary = Color(0xFFFFFFFF)
val AarvoSecondaryContainer = Color(0xFFFFE6CC)
val AarvoOnSecondaryContainer = Color(0xFF4A2100)
val AarvoBackground = Color(0xFFFBFAFF)
val AarvoSurface = Color(0xFFFFFFFF)
val AarvoSurfaceVariant = Color(0xFFF1EFF7)
val AarvoOnBackground = Color(0xFF15131B)
val AarvoOnSurface = Color(0xFF15131B)
val AarvoOnSurfaceVariant = Color(0xFF625D6B)
val AarvoOutline = Color(0xFFD9D4E2)

val AarvoPrimaryDark = Color(0xFFBBA2FF)
val AarvoOnPrimaryDark = Color(0xFF2D006B)
val AarvoPrimaryContainerDark = Color(0xFF3F119B)
val AarvoOnPrimaryContainerDark = Color(0xFFEDE5FF)
val AarvoSecondaryDark = Color(0xFFFFB870)
val AarvoOnSecondaryDark = Color(0xFF3D2000)
val AarvoSecondaryContainerDark = Color(0xFF6A3900)
val AarvoOnSecondaryContainerDark = Color(0xFFFFE6CC)
val AarvoBackgroundDark = Color(0xFF120E1C)
val AarvoSurfaceDark = Color(0xFF1A1624)
val AarvoSurfaceVariantDark = Color(0xFF302B39)
val AarvoOnBackgroundDark = Color(0xFFF8F3FF)
val AarvoOnSurfaceDark = Color(0xFFF8F3FF)
val AarvoOnSurfaceVariantDark = Color(0xFFCAC3D1)
val AarvoOutlineDark = Color(0xFF77717F)
