package com.aarvo.ui.theme

import androidx.compose.ui.graphics.Color

// Premium AARVO palette: deep royal violet, warm gold/orange accents, clean luxury surfaces.
val AarvoPrimary = Color(0xFF5B21D6)
val AarvoOnPrimary = Color(0xFFFFFFFF)
val AarvoPrimaryContainer = Color(0xFFEDE5FF)
val AarvoOnPrimaryContainer = Color(0xFF24005F)
val AarvoSecondary = Color(0xFFFF8A00)
val AarvoOnSecondary = Color(0xFFFFFFFF)
val AarvoSecondaryContainer = Color(0xFFFFE8CC)
val AarvoOnSecondaryContainer = Color(0xFF4A2100)
val AarvoBackground = Color(0xFFF8F7FC)
val AarvoSurface = Color(0xFFFFFFFF)
val AarvoSurfaceVariant = Color(0xFFF0EDF7)
val AarvoOnBackground = Color(0xFF17131F)
val AarvoOnSurface = Color(0xFF17131F)
val AarvoOnSurfaceVariant = Color(0xFF625B6D)
val AarvoOutline = Color(0xFFD7D0E3)

val AarvoPrimaryDark = Color(0xFFC8B2FF)
val AarvoOnPrimaryDark = Color(0xFF32006D)
val AarvoPrimaryContainerDark = Color(0xFF46139D)
val AarvoOnPrimaryContainerDark = Color(0xFFEDE5FF)
val AarvoSecondaryDark = Color(0xFFFFB969)
val AarvoOnSecondaryDark = Color(0xFF432000)
val AarvoSecondaryContainerDark = Color(0xFF6A3900)
val AarvoOnSecondaryContainerDark = Color(0xFFFFE8CC)
val AarvoBackgroundDark = Color(0xFF110D19)
val AarvoSurfaceDark = Color(0xFF1B1624)
val AarvoSurfaceVariantDark = Color(0xFF30293A)
val AarvoOnBackgroundDark = Color(0xFFF9F4FF)
val AarvoOnSurfaceDark = Color(0xFFF9F4FF)
val AarvoOnSurfaceVariantDark = Color(0xFFCAC2D2)
val AarvoOutlineDark = Color(0xFF766D80)
